import { Language, Translations, Package, GalleryImage } from './types';

export const DEFAULT_PACKAGES: Package[] = [
  { id: 1, name: 'Basic', imageCount: 5, price: 10, visible: true },
  { id: 2, name: 'Standard', imageCount: 10, price: 18, visible: true },
  { id: 3, name: 'Premium', imageCount: 20, price: 35, visible: true },
];

export const countries = [
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'CA', name: 'Canada' },
  { code: 'AU', name: 'Australia' },
];

export const DEFAULT_GALLERY_IMAGES: GalleryImage[] = [
  { id: 1, beforeSrc: 'https://picsum.photos/seed/before1/800/600', afterSrc: 'https://picsum.photos/seed/after1/800/600' },
  { id: 2, beforeSrc: 'https://picsum.photos/seed/before2/800/600', afterSrc: 'https://picsum.photos/seed/after2/800/600' },
  { id: 3, beforeSrc: 'https://picsum.photos/seed/before3/800/600', afterSrc: 'https://picsum.photos/seed/after3/800/600' },
  { id: 4, beforeSrc: 'https://picsum.photos/seed/before4/800/600', afterSrc: 'https://picsum.photos/seed/after4/800/600' },
  { id: 5, beforeSrc: 'https://picsum.photos/seed/before5/800/600', afterSrc: 'https://picsum.photos/seed/after5/800/600' },
  { id: 6, beforeSrc: 'https://picsum.photos/seed/before6/800/600', afterSrc: 'https://picsum.photos/seed/after6/800/600' },
];

export const translations: Translations = {
  // Header
  aiTouch: { en: 'AI Touch', ar: 'لمسة الذكاء' },
  home: { en: 'Home', ar: 'الرئيسية' },
  designStudio: { en: 'Design Studio', ar: 'استوديو التصميم' },
  adminPanel: { en: 'Admin Panel', ar: 'لوحة التحكم' },
  userView: { en: 'User View', ar: 'عرض المستخدم' },
  login: { en: 'Login', ar: 'تسجيل الدخول' },
  signUp: { en: 'Sign Up', ar: 'إنشاء حساب' },
  logout: { en: 'Logout', ar: 'تسجيل الخروج' },
  dashboard: { en: 'Dashboard', ar: 'لوحة التحكم' },
  welcome: { en: 'Welcome', ar: 'أهلاً' },
  profile: { en: 'Profile', ar: 'الملف الشخصي' },
  subscriptions: { en: 'Subscriptions', ar: 'الاشتراكات' },

  // Home Page
  heroTitle: { en: 'Redesign Your Space with a Single Touch', ar: 'أعد تصميم مساحتك بلمسة واحدة' },
  heroSubtitle: { en: 'Harness the power of AI to visualize new interior designs instantly. Upload a photo and let our technology inspire you.', ar: 'استخدم قوة الذكاء الاصطناعي لتصور تصميمات داخلية جديدة على الفور. حمّل صورة ودع تقنيتنا تلهمك.' },
  tryNow: { en: 'Try Now For Free', ar: 'جرب الآن مجانًا' },
  beforeAfter: { en: 'From Vision to Reality', ar: 'من الرؤية إلى الواقع' },
  
  // Design Studio
  uploadImage: { en: 'Upload an Image', ar: 'تحميل صورة' },
  or: { en: 'or', ar: 'أو' },
  describeChange: { en: 'Describe the change you want to see...', ar: 'صف التغيير الذي تريد رؤيته...' },
  promptPlaceholder: { en: 'e.g., "Make this room minimalist with neutral colors and wooden furniture."', ar: 'مثال: "اجعل هذه الغرفة بسيطة بألوان محايدة وأثاث خشبي."' },
  generate: { en: 'Generate', ar: 'إنشاء' },
  generating: { en: 'Generating...', ar: 'جاري الإنشاء...' },
  original: { en: 'Original', ar: 'الأصلي' },
  aiDesigned: { en: 'AI Designed', ar: 'تصميم الذكاء الاصطناعي' },
  uploadAnImage: { en: 'Upload an image to begin.', ar: 'حمّل صورة للبدء.' },
  errorOccurred: { en: 'An error occurred. Please try again.', ar: 'حدث خطأ. يرجى المحاولة مرة أخرى.' },
  apiKeyError: { en: 'Failed to generate image. Please ensure your API Key is configured correctly.', ar: 'فشل في إنشاء الصورة. يرجى التأكد من أن مفتاح API الخاص بك تم تكوينهم بشكل صحيح.' },
  downloadImage: { en: 'Download Image', ar: 'تحميل الصورة' },
  undo: { en: 'Undo', ar: 'تراجع' },
  redo: { en: 'Redo', ar: 'إعادة' },
  noCredits: { en: 'You have no image credits left. Please subscribe to a plan to continue.', ar: 'ليس لديك رصيد صور متبقي. يرجى الاشتراك في باقة للمتابعة.' },
  goToSubscriptions: { en: 'Go to Subscriptions', ar: 'اذهب للاشتراكات' },


  // Admin Panel & Dashboard
  statistics: { en: 'Statistics', ar: 'الإحصائيات' },
  finances: { en: 'Finances', ar: 'المالية' },
  settings: { en: 'Settings', ar: 'الإعدادات' },
  totalUsers: { en: 'Total Users', ar: 'إجمالي المستخدمين' },
  imagesDesigned: { en: 'Images Designed', ar: 'الصور المصممة' },
  monthlyRevenue: { en: 'Monthly Revenue', ar: 'الإيرادات الشهرية' },
  imageCreationCost: { en: 'Image Creation Cost', ar: 'تكلفة إنشاء الصور' },
  maintenanceMode: { en: 'Maintenance Mode', ar: 'وضع الصيانة' },
  enableMaintenance: { en: 'Enable maintenance mode to take the site offline.', ar: 'قم بتمكين وضع الصيانة لإيقاف الموقع مؤقتًا.' },
  welcomeUser: { en: 'Welcome to your dashboard!', ar: 'أهلاً بك في لوحة التحكم الخاصة بك!' },
  featureInfo: { en: 'More features for your account will be available here soon.', ar: 'المزيد من الميزات لحسابك ستكون متاحة هنا قريبًا.' },
  users: { en: 'Users', ar: 'المستخدمون' },
  userManagement: { en: 'User Management', ar: 'إدارة المستخدمين' },
  searchByNameOrEmail: { en: 'Search by name or email...', ar: 'ابحث بالاسم أو البريد الإلكتروني...' },
  registrationDate: { en: 'Registration Date', ar: 'تاريخ التسجيل' },
  actions: { en: 'Actions', ar: 'الإجراءات' },
  delete: { en: 'Delete', ar: 'حذف' },
  areYouSureDeleteUser: { en: 'Are you sure you want to delete this user? This action cannot be undone.', ar: 'هل أنت متأكد أنك تريد حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.' },
  cancel: { en: 'Cancel', ar: 'إلغاء' },
  userDeleted: { en: 'User deleted successfully.', ar: 'تم حذف المستخدم بنجاح.' },
  costPerImage: { en: 'Cost Per Image ($)', ar: 'التكلفة لكل صورة ($)' },
  saveSettings: { en: 'Save Settings', ar: 'حفظ الإعدادات' },
  settingsSaved: { en: 'Settings saved successfully.', ar: 'تم حفظ الإعدادات بنجاح.' },
  netProfit: { en: 'Net Profit', ar: 'صافي الربح' },
  totalCosts: { en: 'Total Costs', ar: 'التكاليف الإجمالية' },
  userRegistrations: { en: 'User Registrations (Last 6 Months)', ar: 'تسجيلات المستخدمين (آخر 6 أشهر)' },
  noUsersFound: { en: 'No users found.', ar: 'لم يتم العثور على مستخدمين.' },
  packages: { en: 'Packages', ar: 'الباقات' },
  managePackages: { en: 'Manage Packages', ar: 'إدارة الباقات' },
  packageName: { en: 'Package Name', ar: 'اسم الباقة' },
  imageCount: { en: 'Image Count', ar: 'عدد الصور' },
  priceSAR: { en: 'Price (SAR)', ar: 'السعر (ر.س)' },
  visible: { en: 'Visible', ar: 'مرئي' },
  saveChanges: { en: 'Save Changes', ar: 'حفظ التغييرات' },
  packagesSaved: { en: 'Packages saved successfully.', ar: 'تم حفظ الباقات بنجاح.' },
  gallery: { en: 'Gallery', ar: 'المعرض' },
  manageGallery: { en: 'Manage Gallery', ar: 'إدارة المعرض' },
  addNewImage: { en: 'Add New Image', ar: 'إضافة صورة جديدة' },
  beforeImage: { en: 'Before Image', ar: 'الصورة قبل' },
  afterImage: { en: 'After Image', ar: 'الصورة بعد' },
  upload: { en: 'Upload', ar: 'رفع' },
  deleteImageConfirmation: { en: 'Are you sure you want to delete this image pair?', ar: 'هل أنت متأكد أنك تريد حذف زوج الصور هذا؟' },
  imageAdded: { en: 'Image added successfully.', ar: 'تمت إضافة الصورة بنجاح.' },
  imageDeleted: { en: 'Image deleted successfully.', ar: 'تم حذف الصورة بنجاح.' },
  
  // Financial Anomaly Detection
  anomalyDetection: { en: 'Anomaly Detection', ar: 'كشف الحالات الشاذة' },
  financialAnomalies: { en: 'Financial Anomaly Detection', ar: 'كشف الحالات المالية الشاذة' },
  revenueSpikeAlert: { en: 'Revenue Spike Alert', ar: 'تنبيه ارتفاع الإيرادات' },
  highValueCustomers: { en: 'High-Value Customers', ar: 'العملاء ذوو القيمة العالية' },
  rapidPurchaseFlags: { en: 'Rapid Purchase Flags', ar: 'علامات الشراء السريع' },
  chargebackRate: { en: 'Chargeback Rate', ar: 'معدل استرداد المدفوعات' },
  transactionLog: { en: 'Transaction Log', ar: 'سجل المعاملات' },
  searchTransactions: { en: 'Search by user email...', ar: 'ابحث بالبريد الإلكتروني للمستخدم...' },
  transactionId: { en: 'Transaction ID', ar: 'معرف المعاملة' },
  package: { en: 'Package', ar: 'الباقة' },
  amount: { en: 'Amount (SAR)', ar: 'المبلغ (ر.س)' },
  date: { en: 'Date', ar: 'التاريخ' },
  status: { en: 'Status', ar: 'الحالة' },
  flagAsChargeback: { en: 'Flag as Chargeback', ar: 'وضع علامة كاسترداد' },
  completed: { en: 'Completed', ar: 'مكتمل' },
  chargeback: { en: 'Chargeback', ar: 'مسترد' },
  dailyRevenueLast30Days: { en: 'Daily Revenue (Last 30 Days)', ar: 'الإيرادات اليومية (آخر 30 يومًا)' },
  noTransactionsFound: { en: 'No transactions found.', ar: 'لم يتم العثور على معاملات.' },
  topSpenders: { en: 'Top 5 Spenders', ar: 'أعلى 5 منفقين' },
  recentRapidPurchases: { en: 'Recent Rapid Purchases (Last 24h)', ar: 'عمليات الشراء السريعة الأخيرة (آخر 24 ساعة)' },
  totalSpent: { en: 'Total Spent', ar: 'إجمالي الإنفاق' },
  purchases: { en: 'Purchases', ar: 'عمليات شراء' },
  aboveAverage: { en: "Today is {0}% above 30-day average", ar: "اليوم أعلى من متوسط 30 يومًا بنسبة {0}%" },
  belowAverage: { en: "Today is {0}% below 30-day average", ar: "اليوم أقل من متوسط 30 يومًا بنسبة {0}%" },
  noSufficientData: { en: 'Not enough data for comparison.', ar: 'لا توجد بيانات كافية للمقارنة.' },


  // Auth Pages
  createAccount: { en: 'Create Account', ar: 'إنشاء حساب' },
  name: { en: 'Name', ar: 'الاسم' },
  emailAddress: { en: 'Email Address', ar: 'البريد الإلكتروني' },
  password: { en: 'Password', ar: 'كلمة المرور' },
  confirmPassword: { en: 'Confirm Password', ar: 'تأكيد كلمة المرور' },
  country: { en: 'Country', ar: 'الدولة' },
  selectCountry: { en: 'Select Country', ar: 'اختر الدولة' },
  passwordsDoNotMatch: { en: 'Passwords do not match.', ar: 'كلمتا المرور غير متطابقتين.' },
  dontHaveAccount: { en: "Don't have an account?", ar: 'ليس لديك حساب؟' },
  alreadyHaveAccount: { en: 'Already have an account?', ar: 'هل لديك حساب بالفعل؟' },
  userExists: { en: 'User with this email already exists.', ar: 'المستخدم بهذا البريد الإلكتروني موجود بالفعل.' },
  userExistsRedirect: { en: 'Email already registered. Redirecting to login...', ar: 'البريد الإلكتروني مسجل بالفعل. جاري التوجيه إلى صفحة تسجيل الدخول...' },
  invalidCredentials: { en: 'Invalid email or password.', ar: 'البريد الإلكتروني أو كلمة المرور غير صالحة.' },
  adminAccountError: { en: 'This email is reserved. Please use a different email.', ar: 'هذا البريد الإلكتروني محجوز. الرجاء استخدام بريد إلكتروني مختلف.' },
  orSignInWith: { en: 'Or sign in with', ar: 'أو سجل الدخول باستخدام' },

  // Profile & Subscription Page
  accountDetails: { en: 'Account Details', ar: 'تفاصيل الحساب' },
  changePassword: { en: 'Change Password', ar: 'تغيير كلمة المرور' },
  currentPassword: { en: 'Current Password', ar: 'كلمة المرور الحالية' },
  newPassword: { en: 'New Password', ar: 'كلمة المرور الجديدة' },
  confirmNewPassword: { en: 'Confirm New Password', ar: 'تأكيد كلمة المرور الجديدة' },
  updatePassword: { en: 'Update Password', ar: 'تحديث كلمة المرور' },
  passwordUpdated: { en: 'Password updated successfully!', ar: 'تم تحديث كلمة المرور بنجاح!' },
  incorrectPassword: { en: 'Incorrect current password.', ar: 'كلمة المرور الحالية غير صحيحة.' },
  newPasswordsDoNotMatch: { en: 'New passwords do not match.', ar: 'كلمتا المرور الجديدتان غير متطابقتين.' },
  choosePlan: { en: 'Choose Your Plan', ar: 'اختر خطتك' },
  imagesRemaining: { en: 'Images Remaining', ar: 'الصور المتبقية' },
  buyNow: { en: 'Buy Now', ar: 'اشتر الآن' },
  SAR: { en: 'SAR', ar: 'ر.س' },
  images: { en: 'Images', ar: 'صور' },
  popular: { en: 'Popular', ar: 'شائع' },
  youHave: { en: 'You have', ar: 'لديك' },
  yourPlanIs: { en: 'Your current plan is', ar: 'خطتك الحالية هي' },
};